package pl.voltspot.backend.mapper;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class CountryID {
    public static final Map<Integer, String> COUNTRIES;

    static {
        Map<Integer, String> temp = new HashMap<>(125);
        temp.put(1, "Wielka Brytania");
        temp.put(2, "Stany Zjednoczone");
        temp.put(3, "Irlandia");
        temp.put(4, "Hongkong");
        temp.put(5, "Afganistan");
        temp.put(6, "Wyspy Alandzkie");
        temp.put(7, "Albania");
        temp.put(10, "Andora");
        temp.put(15, "Argentyna");
        temp.put(16, "Armenia");
        temp.put(18, "Australia");
        temp.put(19, "Austria");
        temp.put(20, "Azerbejdżan");
        temp.put(22, "Bahrajn");
        temp.put(24, "Barbados");
        temp.put(25, "Białoruś");
        temp.put(26, "Belgia");
        temp.put(33, "Bośnia i Hercegowina");
        temp.put(34, "Botswana");
        temp.put(36, "Brazylia");
        temp.put(37, "Brytyjskie Terytorium Oceanu Indyjskiego");
        temp.put(39, "Bułgaria");
        temp.put(42, "Kambodża");
        temp.put(44, "Kanada");
        temp.put(49, "Chile");
        temp.put(50, "Chiny");
        temp.put(53, "Kolumbia");
        temp.put(58, "Kostaryka");
        temp.put(60, "Chorwacja");
        temp.put(63, "Cypr");
        temp.put(64, "Czechy");
        temp.put(65, "Dania");
        temp.put(68, "Dominikana");
        temp.put(69, "Ekwador");
        temp.put(70, "Egipt");
        temp.put(71, "Salwador");
        temp.put(74, "Estonia");
        temp.put(75, "Etiopia");
        temp.put(77, "Wyspy Owcze");
        temp.put(79, "Finlandia");
        temp.put(80, "Francja");
        temp.put(86, "Gruzja");
        temp.put(87, "Niemcy");
        temp.put(88, "Ghana");
        temp.put(89, "Gibraltar");
        temp.put(90, "Grecja");
        temp.put(95, "Gwatemala");
        temp.put(96, "Guernsey");
        temp.put(104, "Węgry");
        temp.put(105, "Islandia");
        temp.put(106, "Indie");
        temp.put(107, "Indonezja");
        temp.put(108, "Iran");
        temp.put(109, "Irak");
        temp.put(110, "Wyspa Man");
        temp.put(111, "Izrael");
        temp.put(112, "Włochy");
        temp.put(113, "Jamajka");
        temp.put(114, "Japonia");
        temp.put(115, "Jersey");
        temp.put(116, "Jordania");
        temp.put(117, "Kazachstan");
        temp.put(118, "Kenia");
        temp.put(121, "Korea Południowa");
        temp.put(123, "Kirgistan");
        temp.put(125, "Łotwa");
        temp.put(130, "Liechtenstein");
        temp.put(131, "Litwa");
        temp.put(132, "Luksemburg");
        temp.put(133, "Makau");
        temp.put(134, "Macedonia Północna");
        temp.put(137, "Malezja");
        temp.put(140, "Malta");
        temp.put(146, "Meksyk");
        temp.put(148, "Mołdawia");
        temp.put(149, "Monako");
        temp.put(151, "Czarnogóra");
        temp.put(153, "Maroko");
        temp.put(155, "Birma");
        temp.put(156, "Namibia");
        temp.put(158, "Nepal");
        temp.put(159, "Holandia");
        temp.put(161, "Nowa Zelandia");
        temp.put(168, "Norwegia");
        temp.put(169, "Oman");
        temp.put(170, "Pakistan");
        temp.put(172, "Palestyna");
        temp.put(173, "Panama");
        temp.put(175, "Paragwaj");
        temp.put(176, "Peru");
        temp.put(177, "Filipiny");
        temp.put(179, "Polska");
        temp.put(180, "Portugalia");
        temp.put(181, "Portoryko");
        temp.put(182, "Katar");
        temp.put(183, "Reunion");
        temp.put(184, "Rumunia");
        temp.put(185, "Rosja");
        temp.put(186, "Rwanda");
        temp.put(190, "Saint Lucia");
        temp.put(195, "San Marino");
        temp.put(197, "Arabia Saudyjska");
        temp.put(199, "Serbia");
        temp.put(202, "Singapur");
        temp.put(204, "Słowacja");
        temp.put(205, "Słowenia");
        temp.put(208, "RPA");
        temp.put(210, "Hiszpania");
        temp.put(211, "Sri Lanka");
        temp.put(214, "Svalbard i Jan Mayen");
        temp.put(215, "Eswatini");
        temp.put(216, "Szwecja");
        temp.put(217, "Szwajcaria");
        temp.put(219, "Tajwan");
        temp.put(222, "Tajlandia");
        temp.put(227, "Trynidad i Tobago");
        temp.put(228, "Tunezja");
        temp.put(229, "Turcja");
        temp.put(233, "Uganda");
        temp.put(234, "Ukraina");
        temp.put(235, "Zjednoczone Emiraty Arabskie");
        temp.put(237, "Urugwaj");
        temp.put(238, "Uzbekistan");
        temp.put(241, "Wietnam");
        temp.put(250, "Kosowo");

        COUNTRIES = Collections.unmodifiableMap(temp);
    }
}
